name: Gatekeeper
on:
  pull_request:
    branches:
      - dev-mt

jobs:
  verify-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source is main-mt
        run: |
          if [[ "${{ github.head_ref }}" != "main-mt" ]]; then
            echo "❌ ERROR: Merges into dev-mt are ONLY allowed from the main-mt branch."
            exit 1
          else
            echo "✅ SUCCESS: Source branch is main-mt."
          fi
